# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{dietrb}
  s.version = "0.4.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Eloy Duran"]
  s.date = %q{2010-05-30}
  s.default_executable = %q{dietrb}
  s.description = %q{IRB on a diet, for MacRuby / Ruby 1.9}
  s.email = %q{eloy.de.enige@gmail.com}
  s.executables = ["dietrb"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc",
     "TODO"
  ]
  s.files = [
    "LICENSE",
     "README.rdoc",
     "Rakefile",
     "TODO",
     "bin/dietrb",
     "dietrb.gemspec",
     "lib/irb.rb",
     "lib/irb/completion.rb",
     "lib/irb/context.rb",
     "lib/irb/deprecated.rb",
     "lib/irb/ext/colorize.rb",
     "lib/irb/ext/completion.rb",
     "lib/irb/ext/history.rb",
     "lib/irb/ext/macruby.rb",
     "lib/irb/formatter.rb",
     "lib/irb/source.rb",
     "lib/irb/version.rb",
     "spec/colorize_spec.rb",
     "spec/completion_spec.rb",
     "spec/context_spec.rb",
     "spec/formatter_spec.rb",
     "spec/history_spec.rb",
     "spec/regression/context_spec.rb",
     "spec/source_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/alloy/dietrb}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.required_ruby_version = Gem::Requirement.new("~> 1.9")
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{IRB on a diet, for MacRuby / Ruby 1.9}
  s.test_files = [
    "spec/colorize_spec.rb",
     "spec/completion_spec.rb",
     "spec/context_spec.rb",
     "spec/formatter_spec.rb",
     "spec/history_spec.rb",
     "spec/regression/context_spec.rb",
     "spec/source_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

